from typing import List, Tuple, Dict, Union, Any
from collections import defaultdict
import torch
import numpy as np
from functools import partial
import os
from agent_system.environments.prompts import *
from agent_system.environments.base import EnvironmentManagerBase, to_numpy
import copy

def parse_gamefile(infos):
    gamefile = []
    for info in infos:
        if 'extra.gamefile' in info:
            gamefile.append(info['extra.gamefile'])
        else:
            gamefile.append(None)
    return gamefile

def set_gamefile(infos, gamefile):
    for i in range(len(infos)):
        if 'extra.gamefile' in infos[i]:
            infos[i]['extra.gamefile'] = gamefile[i]
        else:
            infos[i]['extra.gamefile'] = None
    return infos


class AlfWorldEnvironmentManager(EnvironmentManagerBase):
    def __init__(self, envs, projection_f, env_name, config=None):
        self.buffers = None
        self.config = config

        # Check if ReBel mode is enabled
        self.use_rebel = (
            config is not None and
            hasattr(config, 'algorithm') and
            hasattr(config.algorithm, 'rebel') and
            getattr(config.algorithm.rebel, 'enable', False)
        )

        # Initialize ReBel components if enabled
        if self.use_rebel:
            from agent_system.environments.env_package.alfworld import (
                BeliefStateParser, GroundTruthTracker, RebelRewardCalculator
            )
            self.belief_parser = BeliefStateParser()
            self.reward_calculator = RebelRewardCalculator(
                alpha=getattr(config.algorithm.rebel, 'alpha', 0.3),
                beta=getattr(config.algorithm.rebel, 'beta', 0.5),
                gamma=getattr(config.algorithm.rebel, 'gamma', 0.2),
                delta=getattr(config.algorithm.rebel, 'delta', 0.1)
            )
            # Track ground truth for each environment
            self.ground_truth_trackers = {}
            # Track cumulative belief state for each environment
            self.cumulative_beliefs = {}  # env_id -> accumulated belief state
            # Track step count for each environment
            self.step_counts = {}  # env_id -> step count
            # NEW: Track task plans for each environment (filled before first step)
            self.task_plans = {}  # env_id -> parsed planning JSON
        else:
            self.belief_parser = None
            self.reward_calculator = None
            self.ground_truth_trackers = {}
            self.cumulative_beliefs = {}
            self.step_counts = {}
            self.task_plans = {}

        super().__init__(envs, projection_f, env_name)

    def reset(self):
        text_obs, image_obs, infos = self.envs.reset()
        self.gamefile = parse_gamefile(infos)

        # Initialize history buffer
        if self.buffers is not None:
            self.buffers.clear()
        self.buffers = [[] for _ in range(len(text_obs))]
        self.tasks = []
        self.pre_text_obs = text_obs
        self.extract_task(text_obs)

        # Initialize ReBel ground truth trackers
        if self.use_rebel:
            from agent_system.environments.env_package.alfworld import GroundTruthTracker
            self.ground_truth_trackers.clear()
            self.cumulative_beliefs.clear()
            self.step_counts.clear()
            self.task_plans.clear()  # Clear task plans on reset
            # NEW: Initialize history trackers
            self.belief_history = {}  # env_id -> list of predicted belief states
            self.gt_history = {}      # env_id -> list of ground truth states

            for i in range(len(text_obs)):
                tracker = GroundTruthTracker()
                tracker.update_from_observation(text_obs[i])
                self.ground_truth_trackers[i] = tracker

                # IMPROVED: Initialize cumulative belief state from initial observation
                gt_state = tracker.get_ground_truth_state()
                self.cumulative_beliefs[i] = {
                    'world_model': gt_state['object_locations'].copy(),  # Start with visible objects
                    'task_progress': {
                        'subgoal': None,  # First subgoal to be generated by model
                        'status': 'in_progress',
                        'task_goal': gt_state['task_goal']  # Include task goal
                    },
                    'exploration_map': {
                        'visited': set(gt_state['visited']),  # Start with visible locations
                        'unexplored': set()
                    }
                }

                # Initialize step count
                self.step_counts[i] = 0

                # NEW: Initialize history lists
                self.belief_history[i] = []
                self.gt_history[i] = []
                # Record initial ground truth state
                self.gt_history[i].append(gt_state.copy())

        full_text_obs = self.build_text_obs(text_obs, self.envs.get_admissible_commands, init=True)

        return {'text': full_text_obs, 'image': image_obs, 'anchor': text_obs}, infos

    def step(self, text_actions: List[str]):
        full_output = copy.deepcopy(text_actions)

        # For ReBel, plannings is actually beliefs
        actions, valids, beliefs, action_available = self.projection_f(text_actions, self.envs.get_admissible_commands)

        text_obs, image_obs, rewards, dones, infos = self.envs.step(actions)
        self.save_to_history_buffer(self.pre_text_obs, actions, full_output, beliefs)
        self.pre_text_obs = text_obs

        full_text_obs = self.build_text_obs(text_obs, self.envs.get_admissible_commands)
        if infos[0].get("extra.gamefile") is None:
            infos = set_gamefile(infos, self.gamefile)

        # Process each environment
        for i, info in enumerate(infos):
            info['is_action_valid'] = to_numpy(valids[i])
            info['action_available'] = to_numpy(action_available[i])

            # Calculate ReBel intrinsic rewards if enabled
            if self.use_rebel and i in self.ground_truth_trackers:
                # Update ground truth tracker
                self.ground_truth_trackers[i].update_from_observation(text_obs[i], actions[i])
                ground_truth = self.ground_truth_trackers[i].get_ground_truth_state()

                # NEW: Record ground truth state in history
                if i in self.gt_history:
                    self.gt_history[i].append(ground_truth.copy())

                # Parse belief state from model output
                belief_state = self.belief_parser.parse_belief(full_output[i])

                # NEW: Record predicted belief state in history (even if None)
                if i in self.belief_history:
                    self.belief_history[i].append(belief_state)

                if belief_state:
                    # Calculate intrinsic rewards
                    step = len(self.buffers[i])
                    success = info.get('won', False)

                    # Get format validity flags
                    is_format_valid = bool(valids[i])
                    is_action_available = bool(action_available[i])

                    intrinsic_reward, breakdown = self.reward_calculator.calculate_total_intrinsic_reward(
                        belief_state=belief_state,
                        ground_truth=ground_truth,
                        step=step,
                        done=dones[i],
                        success=success,
                        is_format_valid=is_format_valid,
                        is_action_available=is_action_available
                    )

                    # Add intrinsic reward to total reward
                    rewards[i] = float(rewards[i]) + intrinsic_reward

                    # Store reward breakdown in info
                    info['rebel_rewards'] = breakdown
                    info['rebel_intrinsic_reward'] = intrinsic_reward  # For rollout_loop
                    info['belief_state'] = belief_state
                    # NEW: Also store ground truth state for comparison
                    info['ground_truth_state'] = ground_truth

                    # Update cumulative belief state
                    self._update_cumulative_belief(i, belief_state)

                    # Increment step count
                    self.step_counts[i] = self.step_counts.get(i, 0) + 1
                else:
                    # No valid belief state parsed - still give format reward/penalty
                    is_format_valid = bool(valids[i])
                    is_action_available = bool(action_available[i])

                    # Calculate only format reward
                    r_format = self.reward_calculator.calculate_format_reward(
                        is_format_valid=is_format_valid,
                        is_action_available=is_action_available
                    )

                    # Apply format reward
                    intrinsic_reward = self.reward_calculator.delta * r_format
                    rewards[i] = float(rewards[i]) + intrinsic_reward

                    # Store reward breakdown in info
                    info['rebel_rewards'] = {
                        'r_consistency': 0.0,
                        'r_progress': 0.0,
                        'r_exploration': 0.0,
                        'r_format': r_format,
                        'r_intrinsic_total': intrinsic_reward
                    }
                    info['rebel_intrinsic_reward'] = intrinsic_reward  # For rollout_loop
                    info['belief_state'] = None
                    # NEW: Still store ground truth for analysis
                    info['ground_truth_state'] = ground_truth

        next_observations = {'text': full_text_obs, 'image': image_obs, 'anchor': text_obs}
        rewards = to_numpy(rewards)
        dones = to_numpy(dones)

        return next_observations, rewards, dones, infos

    def extract_task(self, text_obs: List[str]):
        for obs in text_obs:
            task_start = obs.find('Your task is to: ')

            if task_start != -1:
                self.tasks.append(obs[task_start + len('Your task is to: '):].strip())
            else:
                raise ValueError("Task description not found in text observation.")

    def build_text_obs(self, text_obs: List[str], admissible_actions: List[List[str]], init: bool = False, history_length: int = 2) -> List[str]:
        """
        This function builds the text observation for the agent.
        """
        postprocess_text_obs = []

        # Select template based on ReBel mode
        if self.use_rebel:
            from agent_system.environments.env_package.alfworld import (
                ALFWORLD_TEMPLATE_REBEL, ALFWORLD_TEMPLATE_NO_HIS_REBEL
            )
            _ALFWORLD_TEMPLATE_NO_HIS = ALFWORLD_TEMPLATE_NO_HIS_REBEL
            _ALFWORLD_TEMPLATE = ALFWORLD_TEMPLATE_REBEL
        else:
            # Default basic template
            _ALFWORLD_TEMPLATE_NO_HIS = ALFWORLD_TEMPLATE_NO_HIS
            _ALFWORLD_TEMPLATE = ALFWORLD_TEMPLATE

        for i in range(len(text_obs)):
            # exclude 'help' in admissible_actions[i]
            reformatted_admissible_actions = "\n ".join(f"'{s}'" for s in admissible_actions[i] if s != 'help')

            # Get task description
            task_description = self.tasks[i] if i < len(self.tasks) else "Unknown task"

            if init or history_length <= 0:
                # Initial observation - no history
                if self.use_rebel:
                    obs = _ALFWORLD_TEMPLATE_NO_HIS.format(
                        task_description=task_description,
                        observation=text_obs[i],
                        admissible_actions=reformatted_admissible_actions
                    )
                else:
                    obs = _ALFWORLD_TEMPLATE_NO_HIS.format(
                        observation=text_obs[i],
                        admissible_actions=reformatted_admissible_actions
                    )
            else:
                # With history
                recent_history = self.buffers[i][-history_length:]
                action_history = ""
                for j, record in enumerate(recent_history):
                    step_number = len(self.buffers[i]) - len(recent_history) + j + 1
                    action = record["action"]
                    env_obs = record["text_obs"]
                    action_history += f"\n[Step {step_number}: Observation: '{env_obs}', Action: '{action}']"

                if self.use_rebel:
                    # Get cumulative belief states for ReBel
                    world_state, task_state, explore_map_state = self._format_belief_state_for_prompt(i)
                    current_step = len(self.buffers[i])
                    step_count = self.step_counts.get(i, 0)

                    obs = _ALFWORLD_TEMPLATE.format(
                        task_description=task_description,
                        current_step=current_step,
                        step_count=step_count,
                        observation=text_obs[i],
                        world_state=world_state,
                        task_state=task_state,
                        explore_map_state=explore_map_state,
                        admissible_actions=reformatted_admissible_actions,
                        history=action_history.strip()
                    )
                else:
                    obs = _ALFWORLD_TEMPLATE.format(
                        history=action_history.strip(),
                        observation=text_obs[i],
                        admissible_actions=reformatted_admissible_actions
                    )

            postprocess_text_obs.append(obs)

        return postprocess_text_obs

    def save_to_history_buffer(self, text_obs, actions, text_actions, beliefs=[]):
        for i in range(len(actions)):
            self.buffers[i].append({
                'text_obs': text_obs[i],
                'action': actions[i],
                'full_output': text_actions[i],
                'belief': beliefs[i] if i < len(beliefs) else None
            })

    def _update_cumulative_belief(self, env_id: int, belief_state: Dict[str, Any]):
        """Update cumulative belief state for an environment"""
        if env_id not in self.cumulative_beliefs:
            self.cumulative_beliefs[env_id] = {
                'world_model': {},
                'task_progress': {'subgoal': None, 'status': 'in_progress'},
                'exploration_map': {'visited': set(), 'unexplored': set()}
            }

        cumulative = self.cumulative_beliefs[env_id]

        # Update world model (accumulate object locations and states)
        world_update = belief_state.get('world_model_update', {}) or {}
        if not isinstance(world_update, dict):
            world_update = {}

        # Safely update found_objects
        found_objects = world_update.get('found_objects', {})
        if isinstance(found_objects, dict) and found_objects:
            cumulative['world_model'].update(found_objects)
        elif isinstance(found_objects, str) and found_objects:
            # Handle case where found_objects is a string (e.g., "apple 1: on countertop 1")
            # Try to parse simple "obj: location" format
            try:
                if ':' in found_objects:
                    parts = found_objects.split(':')
                    if len(parts) == 2:
                        cumulative['world_model'][parts[0].strip()] = parts[1].strip()
            except Exception:
                pass  # Ignore parse errors

        # Safely update state_changes
        state_changes = world_update.get('state_changes', {})
        if isinstance(state_changes, dict) and state_changes:
            cumulative['world_model'].update(state_changes)

        # Update task progress (keep latest)
        task_update = belief_state.get('task_progress_update', {}) or {}
        if not isinstance(task_update, dict):
            task_update = {}
        if task_update:
            updated_subgoal = task_update.get('updated_subgoal')
            if updated_subgoal and isinstance(updated_subgoal, str):
                cumulative['task_progress']['subgoal'] = updated_subgoal
            subgoal_status = task_update.get('subgoal_status')
            if subgoal_status and isinstance(subgoal_status, str):
                cumulative['task_progress']['status'] = subgoal_status

        # Update exploration map (accumulate visited, update unexplored)
        explore_update = belief_state.get('exploration_map_update', {}) or {}
        if not isinstance(explore_update, dict):
            explore_update = {}

        # Safely update newly_visited
        newly_visited = explore_update.get('newly_visited', [])
        if isinstance(newly_visited, list):
            for loc in newly_visited:
                if isinstance(loc, str) and loc:
                    cumulative['exploration_map']['visited'].add(loc)
        elif isinstance(newly_visited, str) and newly_visited:
            cumulative['exploration_map']['visited'].add(newly_visited)

        # Safely update next_priority
        next_priority = explore_update.get('next_priority', [])
        if isinstance(next_priority, list):
            cumulative['exploration_map']['unexplored'] = set(
                p for p in next_priority if isinstance(p, str) and p
            )
        elif isinstance(next_priority, str) and next_priority:
            cumulative['exploration_map']['unexplored'] = {next_priority}

    def _format_belief_state_for_prompt(self, env_id: int) -> tuple:
        """Format cumulative belief state for inclusion in prompt"""
        if env_id not in self.cumulative_beliefs:
            return "None", "None", "None"

        cumulative = self.cumulative_beliefs[env_id]

        # Format world model
        world_items = []
        for obj, loc_or_state in cumulative['world_model'].items():
            world_items.append(f"  - {obj}: {loc_or_state}")
        world_state = "\n".join(world_items) if world_items else "  (No objects discovered yet)"

        # Format task progress - NOW includes planning information
        task_progress = cumulative['task_progress']
        task_state = ""

        # Add main goal if available (from planning)
        main_goal = task_progress.get('main_goal', '')
        if main_goal:
            task_state += f"  - Main Goal: {main_goal}\n"

        # Add plan steps if available (from planning)
        plan_steps = task_progress.get('plan', [])
        if plan_steps:
            task_state += "  - Plan:\n"
            for j, step in enumerate(plan_steps):
                if isinstance(step, dict):
                    subgoal = step.get('subgoal', f'Step {j+1}')
                    task_state += f"      {j+1}. {subgoal}\n"
                else:
                    task_state += f"      {j+1}. {step}\n"

        # Add current subgoal and status
        task_state += f"  - Current subgoal: {task_progress.get('subgoal', 'Not set')}\n"
        task_state += f"  - Status: {task_progress.get('status', 'in_progress')}"

        # Format exploration map
        visited = cumulative['exploration_map']['visited']
        unexplored = cumulative['exploration_map']['unexplored']
        explore_state = f"  - Visited: {', '.join(visited) if visited else 'None'}\n"
        explore_state += f"  - Unexplored: {', '.join(unexplored) if unexplored else 'None'}"

        return world_state, task_state, explore_state

    # ═══════════════════════════════════════════════════════════════════════════════
    # NEW: Planning Support Methods - Run BEFORE main interaction loop
    # ═══════════════════════════════════════════════════════════════════════════════

    def get_planning_prompts(self) -> List[str]:
        """
        Get planning prompts for all environments.
        Should be called BEFORE the main interaction loop starts.
        Returns a list of planning prompts, one for each environment.
        """
        if not self.use_rebel:
            return []

        from agent_system.environments.env_package.alfworld import ALFWORLD_PLANNING_PROMPT_REBEL

        planning_prompts = []
        for i in range(len(self.tasks)):
            # Format the planning prompt with task description and initial observation
            reformatted_admissible_actions = "\n ".join(
                f"'{s}'" for s in self.envs.get_admissible_commands[i] if s != 'help'
            )

            prompt = ALFWORLD_PLANNING_PROMPT_REBEL.format(
                task_description=self.tasks[i],
                observation=self.pre_text_obs[i],
                admissible_actions=reformatted_admissible_actions
            )
            planning_prompts.append(prompt)

        return planning_prompts

    def set_task_plans(self, plans: List[dict]):
        """
        Set task plans for all environments.
        Should be called after running planning prompts through the model.

        Args:
            plans: List of parsed planning JSON dicts, one per environment.
                   Each dict should have: main_goal, target_objects, target_receptacle,
                   likely_locations, plan_steps, success_criteria
        """
        if not self.use_rebel:
            return

        for i, plan in enumerate(plans):
            if plan is not None and isinstance(plan, dict):
                self.task_plans[i] = plan

                # Also update cumulative beliefs with planning information
                if i in self.cumulative_beliefs:
                    task_progress = self.cumulative_beliefs[i].get('task_progress', {})
                    task_progress['main_goal'] = plan.get('main_goal', '')
                    task_progress['plan'] = plan.get('plan_steps', [])
                    task_progress['target_objects'] = plan.get('target_objects', [])
                    task_progress['target_receptacle'] = plan.get('target_receptacle', '')
                    task_progress['success_criteria'] = plan.get('success_criteria', '')

                    # Set first subgoal from plan
                    plan_steps = plan.get('plan_steps', [])
                    if plan_steps and len(plan_steps) > 0:
                        first_step = plan_steps[0]
                        if isinstance(first_step, dict):
                            task_progress['subgoal'] = first_step.get('subgoal', '')
                        elif isinstance(first_step, str):
                            task_progress['subgoal'] = first_step

                    self.cumulative_beliefs[i]['task_progress'] = task_progress

                    # Also set exploration priorities from likely_locations
                    likely_locs = plan.get('likely_locations', [])
                    if likely_locs:
                        self.cumulative_beliefs[i]['exploration_map']['unexplored'] = set(likely_locs)

    def has_task_plans(self) -> bool:
        """Check if task plans have been set."""
        return len(self.task_plans) > 0

    def parse_planning_output(self, outputs: List[str]) -> List[dict]:
        """
        Parse model outputs from planning prompts into structured plan dicts.

        Args:
            outputs: List of model output strings (should be JSON)

        Returns:
            List of parsed plan dicts (or None for failed parses)
        """
        import json
        import re

        plans = []
        for output in outputs:
            try:
                # Try to extract JSON from the output
                # First, try direct JSON parse
                plan = json.loads(output.strip())
                plans.append(plan)
            except json.JSONDecodeError:
                # Try to find JSON block in the output
                json_match = re.search(r'\{[\s\S]*\}', output)
                if json_match:
                    try:
                        plan = json.loads(json_match.group())
                        plans.append(plan)
                    except json.JSONDecodeError:
                        plans.append(None)
                else:
                    plans.append(None)

        return plans


    def _process_batch(self, batch_idx, total_batch_list, total_infos, success):
        # Find the last entry with active masks
        for i in reversed(range(len(total_batch_list[batch_idx]))):
            batch_item = total_batch_list[batch_idx][i]
            if batch_item['active_masks']:
                info = total_infos[batch_idx][i]
                won_value = float(info['won'])
                success['success_rate'].append(won_value)

                # Process game file if it exists
                gamefile = info.get("extra.gamefile")
                if gamefile:
                    self._process_gamefile(gamefile, won_value, success)
                return  # Exit after finding the first active mask

    def _process_gamefile(self, gamefile, won_value, success):
        tasks = [
            "pick_and_place",
            "pick_two_obj_and_place",
            "look_at_obj_in_light",
            "pick_heat_then_place_in_recep",
            "pick_cool_then_place_in_recep",
            "pick_clean_then_place_in_recep",
        ]

        for task in tasks:
            if task in gamefile:
                success[f"{task}_success_rate"].append(won_value)
                break


class SciWorldEnvironmentManager(EnvironmentManagerBase):
    def __init__(self, envs, projection_f, env_name, config=None):
        self.buffers = None
        self.config = config
        self.plannings = []
        super().__init__(envs, projection_f, env_name)

    def reset(self):
        text_obs, infos = self.envs.reset()

        # initialize the history buffer
        if self.buffers is not None:
            self.buffers.clear()
        self.buffers = [[] for _ in range(len(text_obs))]
        self.plannings = ["No plan."] * len(text_obs)
        self.tasks = []
        self.pre_text_obs = text_obs
        self.extract_task_descriptions(infos)

        full_text_obs = self.build_text_obs(text_obs, [info['available_actions'] for info in infos], init=True)
        return {'text': full_text_obs, 'anchor': text_obs}, infos

    def step(self, text_actions: List[str]):
        full_output = copy.deepcopy(text_actions)
        meta_think = self.config is not None and self.config.env.sciworld.meta_think if hasattr(self.config.env, 'sciworld') and hasattr(self.config.env.sciworld, 'meta_think') else False
        actions, valids, action_available = self.projection_f(text_actions, meta_think=meta_think, available_actions=self.envs.get_possible_actions)

        plannings = []
        if meta_think:
            for action in text_actions:
                planning = None
                if "<planning>" in action and "</planning>" in action:
                    start_tag = "<planning>"
                    end_tag = "</planning>"
                    start_idx = action.find(start_tag)
                    end_idx = action.find(end_tag)
                    if start_idx != -1 and end_idx != -1:
                        planning = action[start_idx + len(start_tag):end_idx].strip()
                plannings.append(planning)
        else:
            plannings = [None] * len(text_actions)

        text_obs, rewards, dones, infos = self.envs.step(actions)
        self.save_to_history_buffer(self.pre_text_obs, actions, full_output, plannings)
        self.pre_text_obs = text_obs

        full_text_obs = self.build_text_obs(text_obs, [info['available_actions'] for info in infos])

        # add action_valid to infos
        for i, info in enumerate(infos):
            info['is_action_valid'] = to_numpy(valids[i])
            info['full_output'] = full_output[i]
            info['action_available'] = to_numpy(action_available[i])
            info['score'] = info.get('score', -1)

        next_observations = {'text': full_text_obs, 'anchor': text_obs}
        rewards = to_numpy(rewards)
        dones = to_numpy(dones)

        return next_observations, rewards, dones, infos

    def extract_task_descriptions(self, infos: List[dict]):
        for info in infos:
            if 'task_description' in info:
                self.tasks.append(info['task_description'])
            else:
                self.tasks.append("Unknown task")

    def build_text_obs(self, text_obs: List[str], available_actions: List[List[str]], init: bool = False, history_length: int = 2) -> List[str]:
        """
        This function builds the text observation for the agent.
        """
        postprocess_text_obs = []
        if self.meta_think:
            _SCIWORLD_TEMPLATE_NO_HIS = SCIWORLD_TEMPLATE_NO_HIS_MC
            _SCIWORLD_TEMPLATE = SCIWORLD_TEMPLATE_MC
        else:
            _SCIWORLD_TEMPLATE_NO_HIS = SCIWORLD_TEMPLATE_NO_HIS
            _SCIWORLD_TEMPLATE = SCIWORLD_TEMPLATE

        for i in range(len(text_obs)):
            if init or history_length <= 0:
                obs = _SCIWORLD_TEMPLATE_NO_HIS.format(
                    task_description=self.tasks[i],
                    current_observation=text_obs[i],
                    available_actions=available_actions[i]
                )
            else:
                all_actions = [record["action"] for record in self.buffers[i]]
                recent_history = self.buffers[i][-history_length:]
                recent_start_index = len(self.buffers[i]) - history_length
                valid_history_length = len(recent_history)
                action_history = ""

                for j in range(recent_start_index):
                    action = all_actions[j]
                    step_number = j + 1
                    action_history += f"\n[Step {step_number}, Action {step_number}: '{action}']"

                for j, record in enumerate(recent_history):
                    step_number = recent_start_index + j + 1
                    env_obs = record["text_obs"]
                    action = record["action"]
                    action_history += f"\n[Step {step_number}, Observation {step_number}: '{env_obs}', Action {step_number}: '{action}']"

                if self.config is not None and hasattr(self.config.env, 'sciworld') and hasattr(self.config.env.sciworld, 'meta_think') and self.config.env.sciworld.meta_think:
                    history_think_length = min(3, len(self.buffers[i]))
                    start_index = len(self.buffers[i]) - history_think_length
                    action_history += "\n- recent reasoning process: \n" 
                    for j, record in enumerate(self.buffers[i][-history_think_length:]):
                        step_number = start_index + j + 1
                        action_history += f"[Step {step_number}, output {step_number}: '{record['full_output']}']\n"

                    obs = _SCIWORLD_TEMPLATE.format(
                        task_description=self.tasks[i],
                        step_count=len(self.buffers[i]),
                        history_length=valid_history_length,
                        action_history=action_history.strip(),
                        current_step=len(self.buffers[i]) + 1,
                        current_observation=text_obs[i],
                        planning=self.plannings[i],
                        available_actions=available_actions[i]
                    )
                else:
                    obs = _SCIWORLD_TEMPLATE.format(
                        task_description=self.tasks[i],
                        step_count=len(self.buffers[i]),
                        history_length=valid_history_length,
                        action_history=action_history.strip(),
                        current_step=len(self.buffers[i]) + 1,
                        current_observation=text_obs[i],
                        available_actions=available_actions[i]
                    )

            postprocess_text_obs.append(obs)

        return postprocess_text_obs

    def save_to_history_buffer(self, text_obs, actions, text_actions=None, plannings=None):
        for i in range(len(actions)):
            if text_actions:
                self.buffers[i].append({'text_obs': text_obs[i], 'action': actions[i], 'full_output': text_actions[i]})
            else:
                self.buffers[i].append({'text_obs': text_obs[i], 'action': actions[i]})

        if plannings:
            for i in range(len(plannings)):
                if plannings[i] is not None:
                    self.plannings[i] = plannings[i]

    def _process_batch(self, batch_idx, total_batch_list, total_infos, success):
        # Find the last entry with active masks
        for i in reversed(range(len(total_batch_list[batch_idx]))):
            batch_item = total_batch_list[batch_idx][i]
            if batch_item['active_masks']:
                info = total_infos[batch_idx][i]
                won_value = float(info['won'])
                success['success_rate'].append(won_value)
                return

    def _set_meta_think(self, type: bool):
        self.meta_think = type

class WebshopEnvironmentManager(EnvironmentManagerBase):
    def __init__(self, envs, projection_f, env_name):
        self.buffers = None
        super().__init__(envs, projection_f, env_name)
    
    def reset(self) -> Dict[str, Any]:
        obs, infos = self.envs.reset()
        self.tasks = self.extract_task(obs)
        obs = self.format_obs(obs)
        # infos = [None] * self.envs.num_envs
        observations = {'text': self.build_text_obs(obs, infos, init=True), 
                        'image': None, 
                        'anchor': obs.copy()
                        }
        self.pre_text_obs = obs
        # initialize the history buffer
        if self.buffers is not None:
            self.buffers.clear()
        self.buffers = [[] for _ in range(len(infos))]
        # initialize belief states with tasks
        env_ids = list(range(len(infos)))
        try:
            self.belief_mgr.reset(env_ids=env_ids, task_desc=self.tasks)
        except Exception:
            self.belief_mgr.reset(env_ids=env_ids, task_desc=None)
        return observations, infos

    def step(self, text_actions: List[str]):
        actions, valids = self.projection_f(text_actions)
        next_obs, rewards, dones, infos = self.envs.step(actions)

        next_obs = self.format_obs(next_obs)

        self.save_to_history_buffer(self.pre_text_obs, actions)
        self.pre_text_obs = next_obs

        next_observations = {
            'text': self.build_text_obs(next_obs, infos),
            'image': None,
            'anchor': next_obs.copy()
        }
        # add action_valid to infos
        for i, info in enumerate(infos):
            info['is_action_valid'] = to_numpy(valids[i])
            # update belief state and attach snapshot
            try:
                anchor_obs = self.pre_text_obs[i]
                self.belief_mgr.step_update(
                    env_id=i,
                    observation=anchor_obs,
                    action=actions[i],
                    info=info,
                    reward=float(rewards[i]),
                )
                snap = self.belief_mgr.snapshot(i)
                info['belief'] = {
                    'step_idx': snap.step_idx,
                    'world_model': snap.world_model,
                    'task_progress': snap.task_progress,
                    'exploration_map': {
                        'visited_rooms': list(snap.exploration_map.get('visited_rooms', [])),
                        'visited_objects': list(snap.exploration_map.get('visited_objects', [])),
                    },
                    'notes': snap.notes,
                }
            except Exception:
                pass

        rewards = to_numpy(rewards)
        dones = to_numpy(dones)

        return next_observations, rewards, dones, infos

    def extract_task(self, text_obs: List[str]):
        tasks = []
        for obs in text_obs:
            parts = obs.split(" [SEP] ")
            assert parts[1]=='Instruction:'
            tasks.append(parts[2])
        return tasks
    
    def format_obs(self, text_obs):
        postprocess_text_obs = []
        for i in range(len(text_obs)):
            parts = text_obs[i].split(" [SEP] ")
            # the index of self.tasks[i] in parts
            try:
                index = parts.index(self.tasks[i])
                reformatted_obs = " [SEP] ".join(f"'{p}'" for p in parts[index+1:])
            except:
                reformatted_obs = text_obs[i]

            postprocess_text_obs.append(reformatted_obs)

        return postprocess_text_obs
    
    def format_avail_actions(self, avail):
        actions = []

        for key in avail.keys():
            if key not in ["has_search_bar", "clickables"]:
                raise ValueError(f"Unknown key in available actions: {key}")

        if avail["has_search_bar"]:
            actions.append("search[<your query>]")

        for txt in avail["clickables"]:
            actions.append(f"click[{txt}]")

        return actions

    def save_to_history_buffer(self, text_obs, actions):
        for i in range(len(actions)):
            self.buffers[i].append({'text_obs': text_obs[i], 'action': actions[i], "full_output": ""})
            
    def build_text_obs(self, text_obs: List[str], infos: List[List[str]], init: bool = False, history_length: int = 2) -> List[str]:
        """
        This function builds the text observation for the agent.
        """
        postprocess_text_obs = []
        for i in range(len(text_obs)):
            
            available_actions = self.format_avail_actions(infos[i]['available_actions'])
            reformatted_available_actions = "\n".join(f"'{s}'," for s in available_actions)

            if init or history_length <= 0:
                obs = WEBSHOP_TEMPLATE_NO_HIS.format(
                    task_description=self.tasks[i],
                    current_observation=text_obs[i],
                    available_actions=reformatted_available_actions
                )
            else:
                # Get last `history_length` steps
                recent_history = self.buffers[i][-history_length:]
                valid_history_length = len(recent_history)
                start_index = len(self.buffers[i]) - valid_history_length
                action_history = ""
                for j, record in enumerate(recent_history):
                    step_number = start_index + j + 1
                    action = record["action"]
                    env_obs = record["text_obs"]
                    action_history += f"\n[Observation {step_number}: '{env_obs}', Action {step_number}: '{action}']"
                
                obs = WEBSHOP_TEMPLATE.format(
                    task_description=self.tasks[i],
                    step_count=len(self.buffers[i]),
                    history_length=valid_history_length,
                    action_history=action_history.strip(),
                    current_step=len(self.buffers[i]) + 1,
                    current_observation=text_obs[i],
                    available_actions=reformatted_available_actions
                )
                if len(obs) > 13000:
                    print(f"Warning len(obs)={len(obs)} is too long")
                    obs = WEBSHOP_TEMPLATE_NO_HIS.format(
                        task_description=self.tasks[i],
                        current_observation=text_obs[i],
                        available_actions=reformatted_available_actions
                    )

            postprocess_text_obs.append(obs)

        return postprocess_text_obs

    def _process_batch(self, batch_idx, total_batch_list, total_infos, success):
        for i in reversed(range(len(total_batch_list[batch_idx]))):
            batch_item = total_batch_list[batch_idx][i]
            if batch_item['active_masks']:
                info = total_infos[batch_idx][i]
                won_value = float(info['won'])
                score_value = float(info['task_score'])
                success['success_rate'].append(won_value)
                success['webshop_task_score (not success_rate)'].append(score_value)
                return


def make_envs(config):
    """
    Create enviroments
    """
    print("[DEBUG make_envs] Starting make_envs()")
    # check if config.env.rollout.n is an integer
    if not isinstance(config.env.rollout.n, int):
        raise ValueError("config.env.rollout.n should be an integer")
    group_n = config.env.rollout.n if config.env.rollout.n > 0 else 1
    print(f"[DEBUG make_envs] group_n={group_n}, env_name={config.env.env_name}")

    if "alfworld" in config.env.env_name.lower():
        print("[DEBUG make_envs] Creating ALFWorld environments")
        from agent_system.environments.env_package.alfworld import build_alfworld_envs, alfworld_projection, alfworld_projection_rebel

        if config.env.env_name == 'alfworld/AlfredThorEnv':
            alf_config_path = os.path.join(os.path.dirname(__file__), 'env_package/alfworld/configs/config_tw.yaml')
        elif config.env.env_name == 'alfworld/AlfredTWEnv':
            alf_config_path = os.path.join(os.path.dirname(__file__), 'env_package/alfworld/configs/config_tw.yaml')
        else:
            raise ValueError(f"Unsupported environment: {config.env.env_name}")

        print(f"[DEBUG make_envs] alf_config_path={alf_config_path}")
        print(f"[DEBUG make_envs] generalization_level={config.env.alfworld.generalization_level}")

        if config.env.alfworld.generalization_level == 2:
            alf_train_config_path = alf_config_path.replace('config_tw.yaml', 'config_tw_train_ood.yaml')
            alf_test_config_path = alf_config_path.replace('config_tw.yaml', 'config_tw_test_ood.yaml')
            print(f"[DEBUG make_envs] Building training envs (level 2)...")
            train_env_num = config.data.train_batch_size if hasattr(config, 'trainer') and config.trainer.total_epochs > 0 else group_n
            # Fix: Use val_batch_size for validation environments, not group_n
            val_env_num = config.data.val_batch_size if hasattr(config.data, 'val_batch_size') else group_n
            _envs = build_alfworld_envs(alf_train_config_path, config.env.seed, train_env_num, group_n, is_train=True)
            print(f"[DEBUG make_envs] Building validation envs (level 2)...")
            _val_envs = build_alfworld_envs(alf_test_config_path, config.env.seed + 1000, val_env_num, 1, is_train=False, unseen=True)
        elif config.env.alfworld.generalization_level == 1:
            print(f"[DEBUG make_envs] Building training envs (level 1)...")
            train_env_num = config.data.train_batch_size if hasattr(config, 'trainer') and config.trainer.total_epochs > 0 else group_n
            # Fix: Use val_batch_size for validation environments, not group_n
            val_env_num = config.data.val_batch_size if hasattr(config.data, 'val_batch_size') else group_n
            _envs = build_alfworld_envs(alf_config_path, config.env.seed, train_env_num, group_n, is_train=True)
            print(f"[DEBUG make_envs] Building validation envs (level 1)...")
            _val_envs = build_alfworld_envs(alf_config_path, config.env.seed + 1000, val_env_num, 1, is_train=False, unseen=True)
        elif config.env.alfworld.generalization_level == 0:
            print(f"[DEBUG make_envs] Building training envs (level 0)...")
            # Use env.rollout.n for validation-only mode when total_epochs=0
            train_env_num = config.data.train_batch_size if hasattr(config, 'trainer') and config.trainer.total_epochs > 0 else group_n
            # Fix: Use val_batch_size for validation environments, not group_n
            val_env_num = config.data.val_batch_size if hasattr(config.data, 'val_batch_size') else group_n
            print(f"[DEBUG make_envs] train_env_num={train_env_num}, val_env_num={val_env_num}")
            _envs = build_alfworld_envs(alf_config_path, config.env.seed, train_env_num, group_n, is_train=True)
            print(f"[DEBUG make_envs] Training envs built successfully")
            print(f"[DEBUG make_envs] Building validation envs (level 0)...")
            _val_envs = build_alfworld_envs(alf_config_path, config.env.seed + 1000, val_env_num, 1, is_train=False)
            print(f"[DEBUG make_envs] Validation envs built successfully")

        print(f"[DEBUG make_envs] Setting up projection function...")
        # Check if ReBel is enabled
        use_rebel = (hasattr(config, 'algorithm') and
                    hasattr(config.algorithm, 'rebel') and
                    getattr(config.algorithm.rebel, 'enable', False))

        if use_rebel:
            print("[DEBUG make_envs] Using ReBel projection (<belief>/<action>)")
            projection_f = partial(alfworld_projection_rebel)
        else:
            print("[DEBUG make_envs] Using default projection (<think>/<action>)")
            projection_f = partial(alfworld_projection)

        print(f"[DEBUG make_envs] Creating AlfWorldEnvironmentManager for training...")
        envs = AlfWorldEnvironmentManager(_envs, projection_f, config.env.env_name, config)
        print(f"[DEBUG make_envs] Creating AlfWorldEnvironmentManager for validation...")
        val_envs = AlfWorldEnvironmentManager(_val_envs, projection_f, config.env.env_name, config)
        print(f"[DEBUG make_envs] Environment managers created successfully")
        return envs, val_envs
    elif "sciworld" in config.env.env_name.lower():
        from agent_system.environments.env_package.sciworld import build_sciworld_envs, sciworld_projection
        import json
        generalization_level = config.env.sciworld['generalization_level']

        if generalization_level == 2:
            variation_path = 'agent_system/environments/env_package/sciworld/variations_idx/L2_idx.json'
        elif generalization_level == 1:
            variation_path = 'agent_system/environments/env_package/sciworld/variations_idx/L1_idx.json'
        elif generalization_level == 0:
            variation_path = 'agent_system/environments/env_package/sciworld/variations_idx/L0_idx.json'

        with open(variation_path, 'r') as f:
            variations_idx = json.load(f)

        simplifications_preset = config.env.sciworld.get('simplifications_preset', "easy")
        env_step_limit = config.env.sciworld.get('env_step_limit', 100)
        jar_path = config.env.sciworld.get('jar_path', None)

        _envs = build_sciworld_envs(
            seed=config.env.seed, 
            env_num=config.data.train_batch_size, 
            group_n=group_n, 
            simplifications_preset=simplifications_preset,
            env_step_limit=env_step_limit,
            jar_path=jar_path,
            variations_idx=variations_idx['train']
        )

        _val_envs = build_sciworld_envs(
            seed=config.env.seed + 1000, 
            env_num=config.data.val_batch_size, 
            group_n=1, 
            simplifications_preset=simplifications_preset,
            env_step_limit=env_step_limit,
            jar_path=jar_path,
            variations_idx=variations_idx['test']
        )

        # Create projection function
        projection_f = partial(sciworld_projection)

        # Create environment managers
        envs = SciWorldEnvironmentManager(_envs, projection_f, config.env.env_name, config)
        val_envs = SciWorldEnvironmentManager(_val_envs, projection_f, config.env.env_name, config)

        # Give some time for environments to initialize
        import time
        time.sleep((config.data.train_batch_size * group_n + config.data.val_batch_size) * 0.1)

        return envs, val_envs

    elif "webshop" in config.env.env_name.lower():
        from agent_system.environments.env_package.webshop import build_webshop_envs, webshop_projection
        _envs = build_webshop_envs(seed=config.env.seed, env_num=config.data.train_batch_size, group_n=group_n, is_train=True)
        _val_envs = build_webshop_envs(seed=config.env.seed + 1000, env_num=config.data.val_batch_size, group_n=1, is_train=False)

        projection_f = partial(webshop_projection)
        envs = WebshopEnvironmentManager(_envs, projection_f, config.env.env_name)
        val_envs = WebshopEnvironmentManager(_val_envs, projection_f, config.env.env_name)
        import time
        time.sleep((config.data.train_batch_size * group_n + config.data.val_batch_size) * 0.1) # wait for the envs to be ready
        return envs, val_envs
    else:
        print("Environment not supported")
        exit(1)